### PR TITLE
feat: add syntax highlighting to picker results

### PR DESCRIPTION
**Pull request by chrisgrieser**
example how it looks now:

Pasted image 2023-12-07 at 16 04 16@2x

### CODE REVIEW

**Comment by piersolenski** [comment]
I had considered doing this originally, however it does make it less obvious as to what is being matched via the fuzzy searching. Ideally it would be great to have both, but I'm not sure if that is possible?

**Comment by chrisgrieser** [comment]
Sure, that's doable. As colors can vary greatly between different themes, I simply went for `reverse`, as it's discernible everywhere. If standing out too much, `underline` could maybe also work? 
Pasted image 2024-01-07 at 20 55 12@2x

**Comment by piersolenski** [comment]
Dope! I like using colour over underlines to keep it similar to how the default Telescope behaviour works - we just need to make sure the highlight is compatible with other themes!

**Comment by chrisgrieser** [comment]
Yeah, the issue with a color is that it might be not very visible in certain themes. That's why I used `reverse`. It will always be discernible in every theme. 

Already added in the last commit ready to merge

**Comment by piersolenski** [comment]
This is great, thanks!

**Pull request merged**
